CREATE TABLE "pg-drizzle_playlist_track" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_playlist_track_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"playlistId" integer NOT NULL,
	"position" integer NOT NULL,
	"platform" varchar(50) NOT NULL,
	"platformTrackId" varchar(256) NOT NULL,
	"title" varchar(512) NOT NULL,
	"artist" varchar(512) NOT NULL,
	"artworkUrl" text,
	"duration" integer,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_playlist" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_playlist_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"name" varchar(256) NOT NULL,
	"description" text,
	"isPublic" boolean NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_playlist_track" ADD CONSTRAINT "pg-drizzle_playlist_track_playlistId_pg-drizzle_playlist_id_fk" FOREIGN KEY ("playlistId") REFERENCES "public"."pg-drizzle_playlist"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_playlist" ADD CONSTRAINT "pg-drizzle_playlist_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "playlist_track_playlist_idx" ON "pg-drizzle_playlist_track" USING btree ("playlistId");--> statement-breakpoint
CREATE INDEX "playlist_track_position_idx" ON "pg-drizzle_playlist_track" USING btree ("playlistId","position");--> statement-breakpoint
CREATE INDEX "playlist_user_idx" ON "pg-drizzle_playlist" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "playlist_public_idx" ON "pg-drizzle_playlist" USING btree ("isPublic");--> statement-breakpoint
CREATE INDEX "playlist_created_at_idx" ON "pg-drizzle_playlist" USING btree ("createdAt");